layout_spectrum: 0.945781338494271
typography_spectrum: 0.2729708773549646
color:
  brandStrength: 0.7795779788866639
  lightness: 0.6947167895268649
  saturation: 0.6942089113872498
  rhythmicContrast: 0.5920353166293353
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/62ce3aac-0438-4866-88e5-ce08643158f2.png
name: RS Portfolio
navigation:
  - name: Main Page
    url: 'http://raconteursound.com/'
    type: external
  - name: Studio
    url: 'http://raconteursound.com/studio'
    type: external
  - name: Contact Us
    url: 'http://raconteursound.com/contact-us'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a84bd1fd-dab5-447d-b799-e78036605856.png
title: ''
description: ''
