typography_spectrum: 0.6657993199769408
color:
  brandStrength: 0.1551290734205395
  lightness: 0.012086758390069008
  saturation: 0.9345271729398519
  rhythmicContrast: 0.48070562072098255
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
layout_spectrum: 0.16134476009756327
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/62ce3aac-0438-4866-88e5-ce08643158f2.png
name: RS Portfolio
navigation:
  - name: Home
    url: 'http://raconteursound.com'
    type: external
  - name: Studio
    url: 'http://raconteursound.com/studio/'
    type: external
  - name: Contact Us
    url: 'http://raconteursound.com/contact-us/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a84bd1fd-dab5-447d-b799-e78036605856.png
