typography_spectrum: 0.9830577925313264
color:
  brandStrength: 0.5006507565267384
  lightness: 0.8253256822936237
  saturation: 0.6101433041039854
  rhythmicContrast: 0.014111099066212773
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.5615650156978518
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/62ce3aac-0438-4866-88e5-ce08643158f2.png
name: RS Portfolio
navigation:
  - id: 'http://thegrid.ai/raconteursound/'
    url: 'http://thegrid.ai/raconteursound/'
    name: Home
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a84bd1fd-dab5-447d-b799-e78036605856.png
