typography_spectrum: 0.789083314826712
color:
  brandStrength: 0.3177373888902366
  lightness: 0.9568637057673186
  saturation: 0.33457798324525356
  rhythmicContrast: 0.455937129445374
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.8932665928732604
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/62ce3aac-0438-4866-88e5-ce08643158f2.png
name: RS Portfolio
navigation:
  - name: Studio
    url: 'http://raconteursound.com/studio'
    type: external
  - name: Contact
    url: 'http://raconteursound.com/contact-us'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a84bd1fd-dab5-447d-b799-e78036605856.png
title: Raconteur Sound
description: Portfolio
